# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorter_mpl.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindows(object):
    def setupUi(self, MainWindows):
        MainWindows.setObjectName("MainWindows")
        MainWindows.resize(1643, 847)
        MainWindows.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindows.setStyleSheet("")
        MainWindows.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.windows_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.windows_tabWidget.setObjectName("windows_tabWidget")
        self.principal_tab = QtWidgets.QWidget()
        self.principal_tab.setObjectName("principal_tab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.principal_tab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.external_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.external_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.external_groupBox.setMaximumSize(QtCore.QSize(275, 75))
        self.external_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.external_groupBox.setObjectName("external_groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.external_groupBox)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_load = QtWidgets.QPushButton(self.external_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load.sizePolicy().hasHeightForWidth())
        self.btn_load.setSizePolicy(sizePolicy)
        self.btn_load.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_load.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout_4.addWidget(self.btn_load)
        self.btn_save = QtWidgets.QPushButton(self.external_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_save.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        self.verticalLayout.addWidget(self.external_groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.principal_tab)
        self.groupBox_3.setMaximumSize(QtCore.QSize(275, 16777215))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.all_sorting_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.all_sorting_btn.setObjectName("all_sorting_btn")
        self.gridLayout_2.addWidget(self.all_sorting_btn, 7, 1, 1, 1)
        self.metric_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.metric_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.metric_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.metric_comboBox.setObjectName("metric_comboBox")
        self.metric_comboBox.addItem("")
        self.metric_comboBox.addItem("")
        self.metric_comboBox.addItem("")
        self.metric_comboBox.addItem("")
        self.metric_comboBox.addItem("")
        self.metric_comboBox.addItem("")
        self.metric_comboBox.addItem("")
        self.metric_comboBox.addItem("")
        self.metric_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.metric_comboBox, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.all_denoising_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.all_denoising_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.all_denoising_btn.setObjectName("all_denoising_btn")
        self.gridLayout_2.addWidget(self.all_denoising_btn, 7, 0, 1, 1)
        self.TemporalThreshold_Edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.TemporalThreshold_Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.TemporalThreshold_Edit.setObjectName("TemporalThreshold_Edit")
        self.gridLayout_2.addWidget(self.TemporalThreshold_Edit, 0, 1, 1, 1)
        self.min_dist_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.min_dist_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.min_dist_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.min_dist_edit.setObjectName("min_dist_edit")
        self.gridLayout_2.addWidget(self.min_dist_edit, 5, 1, 1, 1)
        self.AmplitudeThreshold_Edit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AmplitudeThreshold_Edit.sizePolicy().hasHeightForWidth())
        self.AmplitudeThreshold_Edit.setSizePolicy(sizePolicy)
        self.AmplitudeThreshold_Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.AmplitudeThreshold_Edit.setObjectName("AmplitudeThreshold_Edit")
        self.gridLayout_2.addWidget(self.AmplitudeThreshold_Edit, 1, 1, 1, 1)
        self.temporal_threshold_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.temporal_threshold_btn.setObjectName("temporal_threshold_btn")
        self.gridLayout_2.addWidget(self.temporal_threshold_btn, 0, 0, 1, 1)
        self.all_in_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.all_in_btn.setObjectName("all_in_btn")
        self.gridLayout_2.addWidget(self.all_in_btn, 8, 0, 1, 2)
        self.n_neighbors_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.n_neighbors_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.n_neighbors_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.n_neighbors_edit.setObjectName("n_neighbors_edit")
        self.gridLayout_2.addWidget(self.n_neighbors_edit, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.amplitude_threshold_btn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amplitude_threshold_btn.sizePolicy().hasHeightForWidth())
        self.amplitude_threshold_btn.setSizePolicy(sizePolicy)
        self.amplitude_threshold_btn.setObjectName("amplitude_threshold_btn")
        self.gridLayout_2.addWidget(self.amplitude_threshold_btn, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.connect_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.connect_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.connect_groupBox.setMaximumSize(QtCore.QSize(275, 300))
        self.connect_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.connect_groupBox.setObjectName("connect_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.connect_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.connect_groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.channel_comboBox = QtWidgets.QComboBox(self.connect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_comboBox.sizePolicy().hasHeightForWidth())
        self.channel_comboBox.setSizePolicy(sizePolicy)
        self.channel_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.channel_comboBox.setObjectName("channel_comboBox")
        self.gridLayout.addWidget(self.channel_comboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.connect_groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.unit_comboBox = QtWidgets.QComboBox(self.connect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit_comboBox.sizePolicy().hasHeightForWidth())
        self.unit_comboBox.setSizePolicy(sizePolicy)
        self.unit_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.unit_comboBox.setObjectName("unit_comboBox")
        self.gridLayout.addWidget(self.unit_comboBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.connect_groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.U2ID_comboBox = QtWidgets.QComboBox(self.connect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U2ID_comboBox.sizePolicy().hasHeightForWidth())
        self.U2ID_comboBox.setSizePolicy(sizePolicy)
        self.U2ID_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.U2ID_comboBox.setObjectName("U2ID_comboBox")
        self.gridLayout.addWidget(self.U2ID_comboBox, 2, 1, 1, 1)
        self.delete_btn = QtWidgets.QPushButton(self.connect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_btn.sizePolicy().hasHeightForWidth())
        self.delete_btn.setSizePolicy(sizePolicy)
        self.delete_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.delete_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout.addWidget(self.delete_btn, 5, 0, 1, 1)
        self.undo_btn = QtWidgets.QPushButton(self.connect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undo_btn.sizePolicy().hasHeightForWidth())
        self.undo_btn.setSizePolicy(sizePolicy)
        self.undo_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.undo_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.undo_btn.setObjectName("undo_btn")
        self.gridLayout.addWidget(self.undo_btn, 5, 1, 1, 1)
        self.denoising_btn = QtWidgets.QPushButton(self.connect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.denoising_btn.sizePolicy().hasHeightForWidth())
        self.denoising_btn.setSizePolicy(sizePolicy)
        self.denoising_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.denoising_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.denoising_btn.setObjectName("denoising_btn")
        self.gridLayout.addWidget(self.denoising_btn, 6, 0, 1, 1)
        self.sorting_btn = QtWidgets.QPushButton(self.connect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sorting_btn.sizePolicy().hasHeightForWidth())
        self.sorting_btn.setSizePolicy(sizePolicy)
        self.sorting_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.sorting_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sorting_btn.setObjectName("sorting_btn")
        self.gridLayout.addWidget(self.sorting_btn, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.connect_groupBox)
        self.log_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.log_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.log_groupBox.setMaximumSize(QtCore.QSize(275, 16777215))
        self.log_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.log_groupBox.setObjectName("log_groupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.log_groupBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.logger = QtWidgets.QPlainTextEdit(self.log_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logger.sizePolicy().hasHeightForWidth())
        self.logger.setSizePolicy(sizePolicy)
        self.logger.setReadOnly(True)
        self.logger.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logger.setObjectName("logger")
        self.horizontalLayout_9.addWidget(self.logger)
        self.verticalLayout.addWidget(self.log_groupBox)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.signals_groupBox = QtWidgets.QGroupBox(self.principal_tab)
        self.signals_groupBox.setObjectName("signals_groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.signals_groupBox)
        self.horizontalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.MplWidget = MplWidget(self.signals_groupBox)
        self.MplWidget.setObjectName("MplWidget")
        self.horizontalLayout_8.addWidget(self.MplWidget)
        self.horizontalLayout_10.addWidget(self.signals_groupBox)
        self.windows_tabWidget.addTab(self.principal_tab, "")
        self.others_tab = QtWidgets.QWidget()
        self.others_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.others_tab.setObjectName("others_tab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.others_tab)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox = QtWidgets.QGroupBox(self.others_tab)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_save_changes = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_changes.sizePolicy().hasHeightForWidth())
        self.btn_save_changes.setSizePolicy(sizePolicy)
        self.btn_save_changes.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn_save_changes.setObjectName("btn_save_changes")
        self.horizontalLayout_11.addWidget(self.btn_save_changes)
        self.btn_run = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_run.sizePolicy().hasHeightForWidth())
        self.btn_run.setSizePolicy(sizePolicy)
        self.btn_run.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayout_11.addWidget(self.btn_run)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_2.addWidget(self.listWidget_3)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.others_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.RawCode = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.RawCode.setObjectName("RawCode")
        self.horizontalLayout_7.addWidget(self.RawCode)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.windows_tabWidget.addTab(self.others_tab, "")
        self.horizontalLayout_6.addWidget(self.windows_tabWidget)
        MainWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1643, 30))
        self.menubar.setObjectName("menubar")
        MainWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindows)
        self.statusbar.setObjectName("statusbar")
        MainWindows.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindows)
        self.windows_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindows)

    def retranslateUi(self, MainWindows):
        _translate = QtCore.QCoreApplication.translate
        MainWindows.setWindowTitle(_translate("MainWindows", "PySorter"))
        self.external_groupBox.setTitle(_translate("MainWindows", "File"))
        self.btn_load.setText(_translate("MainWindows", "Load"))
        self.btn_save.setText(_translate("MainWindows", "Save"))
        self.groupBox_3.setTitle(_translate("MainWindows", "Automatic curation"))
        self.all_sorting_btn.setText(_translate("MainWindows", "Sorting"))
        self.metric_comboBox.setItemText(0, _translate("MainWindows", "manhattan"))
        self.metric_comboBox.setItemText(1, _translate("MainWindows", "euclidean"))
        self.metric_comboBox.setItemText(2, _translate("MainWindows", "chebyshev"))
        self.metric_comboBox.setItemText(3, _translate("MainWindows", "minkowski"))
        self.metric_comboBox.setItemText(4, _translate("MainWindows", "canberra"))
        self.metric_comboBox.setItemText(5, _translate("MainWindows", "braycurtis"))
        self.metric_comboBox.setItemText(6, _translate("MainWindows", "seuclidean"))
        self.metric_comboBox.setItemText(7, _translate("MainWindows", "cosine"))
        self.metric_comboBox.setItemText(8, _translate("MainWindows", "correlation"))
        self.label_4.setText(_translate("MainWindows", "n_neighbors"))
        self.all_denoising_btn.setText(_translate("MainWindows", "Denoising"))
        self.TemporalThreshold_Edit.setText(_translate("MainWindows", "10"))
        self.min_dist_edit.setText(_translate("MainWindows", "0.3"))
        self.AmplitudeThreshold_Edit.setText(_translate("MainWindows", "[-1000, 1000]"))
        self.temporal_threshold_btn.setText(_translate("MainWindows", "Threshold (ms)"))
        self.all_in_btn.setText(_translate("MainWindows", "All In One Step"))
        self.n_neighbors_edit.setText(_translate("MainWindows", "10"))
        self.label_5.setText(_translate("MainWindows", "min_dist"))
        self.label_6.setText(_translate("MainWindows", "metric"))
        self.amplitude_threshold_btn.setText(_translate("MainWindows", "Threshold (mV)"))
        self.connect_groupBox.setTitle(_translate("MainWindows", "Manual curation"))
        self.label_2.setText(_translate("MainWindows", "ChannelID"))
        self.label_3.setText(_translate("MainWindows", "UnitID"))
        self.label.setText(_translate("MainWindows", "SelectedUnit2ID"))
        self.delete_btn.setText(_translate("MainWindows", "Delete"))
        self.undo_btn.setText(_translate("MainWindows", "Undo"))
        self.denoising_btn.setText(_translate("MainWindows", "Denoising"))
        self.sorting_btn.setText(_translate("MainWindows", "Sorting"))
        self.log_groupBox.setTitle(_translate("MainWindows", "Log viewer"))
        self.signals_groupBox.setTitle(_translate("MainWindows", "Spike waveforms"))
        self.windows_tabWidget.setTabText(self.windows_tabWidget.indexOf(self.principal_tab), _translate("MainWindows", "Spikes_View"))
        self.groupBox.setTitle(_translate("MainWindows", "CUSTOM SCRIPTS"))
        self.btn_save_changes.setText(_translate("MainWindows", "SAVE CHANGES"))
        self.btn_run.setText(_translate("MainWindows", "RUN SCRIPT"))
        self.groupBox_2.setTitle(_translate("MainWindows", "PYTHON RAW CODE"))
        self.windows_tabWidget.setTabText(self.windows_tabWidget.indexOf(self.others_tab), _translate("MainWindows", "Python Scripts"))

from QTDesigner.mplwidget import MplWidget
